import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {children}

        {/* <script
          id='drops-widget-script'
          type='text/javascript'
          data-drops-widget='https://althea.drops.house/create-entry?ext_id=Y2h4DRYki'
          src='https://cdn.jsdelivr.net/gh/wondrous-dev/drops-widget@latest/entry-point.js'
        /> */}
        <Script
          id='drops-widget-script'
          type='text/javascript'
          data-drops-widget='https://althea.drops.house/create-entry?ext_id=Y2h4DRYki'
          src='https://cdn.jsdelivr.net/gh/wondrous-dev/drops-widget@latest/index.js'
        />
      </body>
    </html>
  );
}
